import { BoardProfileLayoutTokens } from "./types";

export const DESKTOP_PROFILE_TOKENS: BoardProfileLayoutTokens = {
  frame: {
    rootPadding: "1rem 0.6rem 1.35rem",
    shellMaxWidth: "56rem",
    topStripGap: "1rem",
    topStripMarginBottom: "0.72rem",
    bottomStripMarginTop: "0.92rem",
    boardWidth: "min(calc(100% - 3rem), 48rem)",
    boardMaxWidth: "calc(100% - 3rem)",
    boardHeight: "min(60vh, 40.5rem)",
    boardMaxHeight: "60vh",
    boardAspectRatio: "1.2 / 1",
    boardBorderRadius: "50% / 48.6%",
    boardInnerBorderRadius: "50% / 48.6%",
    boardBorderWidth: "0.9rem",
    boardOutlineWidth: "0.24rem",
    centerSize: "50%",
    seatWidth: "33%",
    seatMaxWidth: "11.8rem",
  },
  match: {
    seatBase: {
      radiusXMultiplier: 1.1,
      radiusYMultiplier: 1.12,
      sideWeightedYMultiplier: false,
      outwardOffsetX: 4,
      outwardOffsetY: 10,
      sideInset: 4.5,
      sideVerticalOffset: 2.8,
      angleOffsetDeg: 0,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 0,
      bottomGroupShiftYPx: 0,
    },
    center: {
      overrides: {},
      spreadBoost: 1,
    },
    dock: {
      handCardWidth: "clamp(4.18rem, 4.35vw, 5.28rem)",
      playedCardWidth: "clamp(3.2rem, 2.8vw, 3.65rem)",
      announcementBlockHeight: "4.75rem",
      handBlockHeight: "6.6rem",
      commandBlockHeight: "3.5rem",
      dockGap: "0.58rem",
      dockBottomOffset: "calc(env(safe-area-inset-bottom) + 0.28rem)",
      bottomDockReserveHeight: "16.35rem",
      handRowMinHeight: "5.5rem",
      handRowTranslateY: "0.08rem",
      commandCompact: true,
    },
    seatPresentation: {
      meTranslateY: 22,
      lowerSideTranslateY: 24,
      topSeatAvatarNudgeY: 0,
      hideTopSeatAvatarNudgeOnProfiles: [],
      hiddenHandCardWidth: "clamp(1.82rem, 5.1vw, 2.02rem)",
      hiddenHandScale: 1,
      hiddenHandRules: {
        tableInsetPx: 72,
        axialInsetReductionPx: 36,
        distanceScale: 1,
        verticalLiftPx: 2.2,
        fanSpacingPx: 12.6,
        fanArcDepthPx: 2.3,
        fanSpreadDeg: 7.4,
        minClearancePx: 10.5,
        handOrigin: "50% 118%",
      },
    },
  },
  lobby: {
    sixPlayerSeat: {
      radiusXMultiplier: 1,
      radiusYMultiplier: 1.02,
      sideWeightedYMultiplier: true,
      outwardOffsetX: 0,
      outwardOffsetY: 0,
      sideInset: 2.6,
      sideVerticalOffset: 1.8,
      angleOffsetDeg: 0,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: -22,
      bottomGroupShiftYPx: -22,
    },
    fourPlayerMobileSeat: null,
    seatCard: {
      minWidth: "9.8rem",
      padding: "0.8rem",
      borderRadius: "0.95rem",
      headerHeight: "2.35rem",
      cardsHeight: "2.8rem",
      actionsHeight: "4.75rem",
      hiddenCardWidth: "clamp(2.15rem, 7vw, 2.35rem)",
      hiddenCardOverlap: -1.2,
    },
  },
};
