import { BoardProfileLayoutTokens } from "./types";

export const PHONE_TALL_PROFILE_TOKENS: BoardProfileLayoutTokens = {
  frame: {
    rootPadding: "0.5rem 0.22rem 0.78rem",
    shellMaxWidth: "56rem",
    topStripGap: "0.78rem",
    topStripMarginBottom: "0.42rem",
    bottomStripMarginTop: "0.42rem",
    boardWidth: "min(calc(100% - 0.45rem), 56rem)",
    boardMaxWidth: "calc(100% - 0.45rem)",
    boardHeight: "min(88%, 41rem)",
    boardMaxHeight: "54vh",
    boardAspectRatio: "auto",
    boardBorderRadius: "50% / 48%",
    boardInnerBorderRadius: "50% / 48%",
    boardBorderWidth: "0.72rem",
    boardOutlineWidth: "0.22rem",
    centerSize: "53%",
    seatWidth: "34%",
    seatMaxWidth: "11.5rem",
  },
  match: {
    topBarTranslateY: "-0.5rem",
    boardTranslateY: "-0.65rem",
    seatBase: {
      radiusXMultiplier: 1,
      radiusYMultiplier: 1,
      sideWeightedYMultiplier: false,
      outwardOffsetX: 3,
      outwardOffsetY: 6,
      sideInset: 3.4,
      sideVerticalOffset: 1.8,
      angleOffsetDeg: 0,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 28,
      bottomGroupShiftYPx: 24,
    },
    center: {
      overrides: {
        centerShiftYPercent: 4,
        playerSpreadXPercent: 37,
        playerSpreadYPercent: 32,
        maxJitterPx: 2,
      },
      spreadBoost: 3.5,
    },
    dock: {
      handCardWidth: "clamp(4.7rem, 14.2dvh, 6.65rem)",
      playedCardWidth: "clamp(3.65rem, 10.7vw, 4.15rem)",
      announcementBlockHeight: "4.75rem",
      announcementTextSizes: {
        tertiary: "0.875rem",
        secondary: "0.875rem",
        primary: "1.25rem",
      },
      handBlockHeight: "6.95rem",
      commandBlockHeight: "3.95rem",
      dockGap: "0.58rem",
      dockBottomOffset: "calc(env(safe-area-inset-bottom) + 3.2rem)",
      bottomDockReserveHeight: "16.9rem",
      handRowMinHeight: "5.8rem",
      handRowTranslateY: "0rem",
      commandCompact: false,
    },
    seatPresentation: {
      avatarFrameSizePx: 58,
      meTranslateY: 20,
      lowerSideTranslateY: 24,
      topSeatAvatarNudgeY: 0,
      hideTopSeatAvatarNudgeOnProfiles: ["phoneTall"],
      hiddenHandCardWidth: "clamp(1.9rem, 5.35vw, 2.1rem)",
      hiddenHandScale: 1,
      hiddenHandRules: {
        tableInsetPx: 42,
        axialInsetReductionPx: 22,
        distanceScale: 0.7,
        verticalLiftPx: 1.5,
        fanSpacingPx: 11,
        fanArcDepthPx: 1.9,
        fanSpreadDeg: 6.3,
        minClearancePx: 9,
        handOrigin: "50% 114%",
      },
      tablePoints: {
        imageHeightMobile: "1.16rem",
      },
    },
  },
  lobby: {
    sixPlayerSeat: {
      radiusXMultiplier: 0.94,
      radiusYMultiplier: 1.1,
      sideWeightedYMultiplier: true,
      outwardOffsetX: 0,
      outwardOffsetY: 0,
      sideInset: 3.8,
      sideVerticalOffset: 14,
      angleOffsetDeg: 0,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 34,
      bottomGroupShiftYPx: 34,
    },
    fourPlayerMobileSeat: {
      radiusXMultiplier: 1.03,
      radiusYMultiplier: 1.08,
      sideWeightedYMultiplier: false,
      outwardOffsetX: 2,
      outwardOffsetY: 6.5,
      sideInset: 2.8,
      sideVerticalOffset: 0,
      angleOffsetDeg: -45,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 54,
      bottomGroupShiftYPx: 48,
    },
    seatCard: {
      minWidth: "10rem",
      padding: "0.8rem",
      borderRadius: "0.95rem",
      headerHeight: "2.35rem",
      cardsHeight: "2.5rem",
      actionsHeight: "4.75rem",
      hiddenCardWidth: "clamp(2.15rem, 7vw, 2.35rem)",
      hiddenCardOverlap: -1.2,
    },
  },
};
