import { BoardProfileLayoutTokens } from "./types";

export const PHONE_WIDE_PROFILE_TOKENS: BoardProfileLayoutTokens = {
  frame: {
    rootPadding: "0.55rem 0.25rem 0.95rem",
    shellMaxWidth: "56rem",
    topStripGap: "0.82rem",
    topStripMarginBottom: "0.52rem",
    bottomStripMarginTop: "0.5rem",
    boardWidth: "min(calc(100% - 1.5rem), 56rem)",
    boardMaxWidth: "calc(100% - 1.5rem)",
    boardHeight: "min(88%, 40rem)",
    boardMaxHeight: "40rem",
    boardAspectRatio: "auto",
    boardBorderRadius: "50% / 48%",
    boardInnerBorderRadius: "50% / 48%",
    boardBorderWidth: "0.72rem",
    boardOutlineWidth: "0.22rem",
    centerSize: "52%",
    seatWidth: "33%",
    seatMaxWidth: "11.2rem",
  },
  match: {
    topBarTranslateY: "-0.55rem",
    boardTranslateY: "-0.45rem",
    seatBase: {
      radiusXMultiplier: 1,
      radiusYMultiplier: 0.96,
      sideWeightedYMultiplier: false,
      outwardOffsetX: 2,
      outwardOffsetY: 4,
      sideInset: 2.8,
      sideVerticalOffset: 1.2,
      angleOffsetDeg: 0,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 20,
      bottomGroupShiftYPx: 18,
    },
    center: {
      overrides: {
        centerShiftYPercent: 1.4,
        playerSpreadXPercent: 36,
        playerSpreadYPercent: 32,
        maxJitterPx: 3.2,
      },
      spreadBoost: 1.2,
    },
    dock: {
      handCardWidth: "clamp(2.42rem, 6.3dvh, 3.14rem)",
      playedCardWidth: "clamp(3.12rem, 4.35vw, 3.25rem)",
      announcementBlockHeight: "4rem",
      announcementTextSizes: {
        tertiary: "0.64rem",
        secondary: "0.7rem",
        primary: "0.92rem",
      },
      handBlockHeight: "3.6rem",
      commandBlockHeight: "3.3rem",
      dockGap: "0.38rem",
      dockBottomOffset: "calc(env(safe-area-inset-bottom) + 3.2rem)",
      bottomDockReserveHeight: "11.35rem",
      handRowMinHeight: "2.6rem",
      handRowTranslateY: "-0.12rem",
      commandCompact: true,
    },
    seatPresentation: {
      avatarFrameSizePx: 56,
      meTranslateY: 16,
      lowerSideTranslateY: 18,
      topSeatAvatarNudgeY: 0,
      hideTopSeatAvatarNudgeOnProfiles: [],
      hiddenHandCardWidth: "clamp(1.65rem, 4.6vw, 1.88rem)",
      hiddenHandScale: 1,
      hiddenHandRules: {
        tableInsetPx: 32,
        axialInsetReductionPx: 20,
        distanceScale: 0.73,
        verticalLiftPx: 1.4,
        fanSpacingPx: 10.3,
        fanArcDepthPx: 1.8,
        fanSpreadDeg: 6,
        minClearancePx: 8.5,
        handOrigin: "50% 112%",
      },
    },
  },
  lobby: {
    sixPlayerSeat: {
      radiusXMultiplier: 0.94,
      radiusYMultiplier: 1.1,
      sideWeightedYMultiplier: true,
      outwardOffsetX: 0,
      outwardOffsetY: 0,
      sideInset: 3.8,
      sideVerticalOffset: 14,
      angleOffsetDeg: 0,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 34,
      bottomGroupShiftYPx: 34,
    },
    fourPlayerMobileSeat: {
      radiusXMultiplier: 1.02,
      radiusYMultiplier: 1.04,
      sideWeightedYMultiplier: false,
      outwardOffsetX: 1.5,
      outwardOffsetY: 4.5,
      sideInset: 2.4,
      sideVerticalOffset: 0,
      angleOffsetDeg: -45,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 44,
      bottomGroupShiftYPx: 40,
    },
    seatCard: {
      minWidth: "9.1rem",
      padding: "0.72rem",
      borderRadius: "0.86rem",
      headerHeight: "2rem",
      cardsHeight: "2.55rem",
      actionsHeight: "4.15rem",
      hiddenCardWidth: "clamp(1.85rem, 5.5vw, 2.05rem)",
      hiddenCardOverlap: -1,
    },
  },
};
