import { BoardProfileLayoutTokens } from "./types";

export const TABLET_PROFILE_TOKENS: BoardProfileLayoutTokens = {
  frame: {
    rootPadding: "0.86rem 0.35rem 1.12rem",
    shellMaxWidth: "56rem",
    topStripGap: "0.92rem",
    topStripMarginBottom: "0.7rem",
    bottomStripMarginTop: "0.82rem",
    boardWidth: "108%",
    boardMaxWidth: "46rem",
    boardHeight: "auto",
    boardMaxHeight: "34rem",
    boardAspectRatio: "1 / 1",
    boardBorderRadius: "50%",
    boardInnerBorderRadius: "50%",
    boardBorderWidth: "0.9rem",
    boardOutlineWidth: "0.24rem",
    centerSize: "55%",
    seatWidth: "35%",
    seatMaxWidth: "11.8rem",
  },
  match: {
    seatBase: {
      radiusXMultiplier: 1.07,
      radiusYMultiplier: 1.08,
      sideWeightedYMultiplier: false,
      outwardOffsetX: 6,
      outwardOffsetY: 12,
      sideInset: 5.1,
      sideVerticalOffset: 3.2,
      angleOffsetDeg: 0,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 0,
      bottomGroupShiftYPx: 0,
    },
    center: {
      overrides: {
        playerSpreadXPercent: 40,
        playerSpreadYPercent: 37,
      },
      spreadBoost: 0,
    },
    dock: {
      handCardWidth: "clamp(5.05rem, 15.2dvh, 7.15rem)",
      playedCardWidth: "clamp(3.05rem, 5vw, 3.6rem)",
      announcementBlockHeight: "4.75rem",
      handBlockHeight: "7.15rem",
      commandBlockHeight: "3.95rem",
      dockGap: "0.58rem",
      dockBottomOffset: "calc(env(safe-area-inset-bottom) + 3.2rem)",
      bottomDockReserveHeight: "17.1rem",
      handRowMinHeight: "5.95rem",
      handRowTranslateY: "0rem",
      commandCompact: true,
    },
    seatPresentation: {
      meTranslateY: 20,
      lowerSideTranslateY: 24,
      topSeatAvatarNudgeY: 0,
      hideTopSeatAvatarNudgeOnProfiles: [],
      hiddenHandCardWidth: "clamp(1.82rem, 5.1vw, 2.02rem)",
      hiddenHandScale: 1,
      hiddenHandRules: {
        tableInsetPx: 64,
        axialInsetReductionPx: 23,
        distanceScale: 0.93,
        verticalLiftPx: 1.8,
        fanSpacingPx: 11.4,
        fanArcDepthPx: 2,
        fanSpreadDeg: 6.6,
        minClearancePx: 9.5,
        handOrigin: "50% 116%",
      },
    },
  },
  lobby: {
    sixPlayerSeat: {
      radiusXMultiplier: 0.96,
      radiusYMultiplier: 1.05,
      sideWeightedYMultiplier: true,
      outwardOffsetX: 0,
      outwardOffsetY: 0,
      sideInset: 3.3,
      sideVerticalOffset: 2.4,
      angleOffsetDeg: 0,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 34,
      bottomGroupShiftYPx: 34,
    },
    fourPlayerMobileSeat: {
      radiusXMultiplier: 1.03,
      radiusYMultiplier: 1.08,
      sideWeightedYMultiplier: false,
      outwardOffsetX: 2,
      outwardOffsetY: 6.5,
      sideInset: 2.8,
      sideVerticalOffset: 0,
      angleOffsetDeg: -45,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 54,
      bottomGroupShiftYPx: 48,
    },
    seatCard: {
      minWidth: "9.65rem",
      padding: "0.78rem",
      borderRadius: "0.92rem",
      headerHeight: "2.3rem",
      cardsHeight: "2.8rem",
      actionsHeight: "4.6rem",
      hiddenCardWidth: "clamp(2.08rem, 6.5vw, 2.3rem)",
      hiddenCardOverlap: -1.16,
    },
  },
};
