import { BoardProfileLayoutTokens } from "./types";

export const TABLET_WIDE_PROFILE_TOKENS: BoardProfileLayoutTokens = {
  frame: {
    rootPadding: "1rem 0.45rem 1.2rem",
    shellMaxWidth: "56rem",
    topStripGap: "0.94rem",
    topStripMarginBottom: "0.72rem",
    bottomStripMarginTop: "0.9rem",
    boardWidth: "min(calc(100% - 2.2rem), 47rem)",
    boardMaxWidth: "calc(100% - 2.2rem)",
    boardHeight: "min(60vh, 39.5rem)",
    boardMaxHeight: "41rem",
    boardAspectRatio: "1.2 / 1",
    boardBorderRadius: "50% / 48.6%",
    boardInnerBorderRadius: "50% / 48.6%",
    boardBorderWidth: "0.86rem",
    boardOutlineWidth: "0.23rem",
    centerSize: "53%",
    seatWidth: "34%",
    seatMaxWidth: "11.5rem",
  },
  match: {
    topBarTranslateY: "-1rem",
    boardTranslateY: "0rem",
    seatBase: {
      radiusXMultiplier: 1.09,
      radiusYMultiplier: 1.08,
      sideWeightedYMultiplier: false,
      outwardOffsetX: 5,
      outwardOffsetY: 11,
      sideInset: 4.9,
      sideVerticalOffset: 3,
      angleOffsetDeg: 0,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 0,
      bottomGroupShiftYPx: 0,
    },
    center: {
      overrides: {},
      spreadBoost: 1,
    },
    dock: {
      handCardWidth: "clamp(4.08rem, 4.35vw, 5.15rem)",
      playedCardWidth: "clamp(3.4rem, 3vw, 3.8rem)",
      announcementBlockHeight: "4.75rem",
      announcementTextSizes: {
        tertiary: "0.875rem",
        secondary: "0.875rem",
        primary: "1.25rem",
      },
      handBlockHeight: "6.45rem",
      commandBlockHeight: "3.5rem",
      dockGap: "0.58rem",
      dockBottomOffset: "calc(env(safe-area-inset-bottom) + 3.2rem)",
      bottomDockReserveHeight: "16.15rem",
      handRowMinHeight: "5.35rem",
      handRowTranslateY: "0.08rem",
      commandCompact: true,
    },
    seatPresentation: {
      avatarFrameSizePx: 56,
      meTranslateY: 22,
      lowerSideTranslateY: 24,
      topSeatAvatarNudgeY: 0,
      hideTopSeatAvatarNudgeOnProfiles: [],
      hiddenHandCardWidth: "clamp(1.82rem, 5.1vw, 2.02rem)",
      hiddenHandScale: 1,
      hiddenHandRules: {
        tableInsetPx: 68,
        axialInsetReductionPx: 29,
        distanceScale: 0.96,
        verticalLiftPx: 0,
        fanSpacingPx: 12,
        fanArcDepthPx: 2.2,
        fanSpreadDeg: 7,
        minClearancePx: 10,
        handOrigin: "50% 117%",
      },
    },
  },
  lobby: {
    sixPlayerSeat: {
      radiusXMultiplier: 0.98,
      radiusYMultiplier: 1.03,
      sideWeightedYMultiplier: true,
      outwardOffsetX: 0,
      outwardOffsetY: 0,
      sideInset: 2.8,
      sideVerticalOffset: 2,
      angleOffsetDeg: 0,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 24,
      bottomGroupShiftYPx: 24,
    },
    fourPlayerMobileSeat: {
      radiusXMultiplier: 1.02,
      radiusYMultiplier: 1.04,
      sideWeightedYMultiplier: false,
      outwardOffsetX: 1.5,
      outwardOffsetY: 4.5,
      sideInset: 2.4,
      sideVerticalOffset: 0,
      angleOffsetDeg: -45,
      sideAngleOffsetDeg: 0,
      topGroupShiftYPx: 44,
      bottomGroupShiftYPx: 40,
    },
    seatCard: {
      minWidth: "9.8rem",
      padding: "0.8rem",
      borderRadius: "0.95rem",
      headerHeight: "2.3rem",
      cardsHeight: "2.8rem",
      actionsHeight: "4.6rem",
      hiddenCardWidth: "clamp(2.08rem, 6.5vw, 2.3rem)",
      hiddenCardOverlap: -1.16,
    },
  },
};
