/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionDotjsonRouteImport } from './routes/version[.]json'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TrucoOnlineRouteImport } from './routes/truco-online'
import { Route as TrucoArgentinoRouteImport } from './routes/truco-argentino'
import { Route as SiteDotwebmanifestRouteImport } from './routes/site[.]webmanifest'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReglasDelTrucoRouteImport } from './routes/reglas-del-truco'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RankingCartasTrucoRouteImport } from './routes/ranking-cartas-truco'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileAccountIdRouteImport } from './routes/profile_.$accountId'
import { Route as MatchSessionIdRouteImport } from './routes/match.$sessionId'
import { Route as LobbySessionIdRouteImport } from './routes/lobby.$sessionId'
import { Route as HistoryMatchIdRouteImport } from './routes/history.$matchId'
import { Route as HelpRulesLangRouteImport } from './routes/help_.rules.$lang'

const VersionDotjsonRoute = VersionDotjsonRouteImport.update({
  id: '/version.json',
  path: '/version.json',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucoOnlineRoute = TrucoOnlineRouteImport.update({
  id: '/truco-online',
  path: '/truco-online',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucoArgentinoRoute = TrucoArgentinoRouteImport.update({
  id: '/truco-argentino',
  path: '/truco-argentino',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteDotwebmanifestRoute = SiteDotwebmanifestRouteImport.update({
  id: '/site.webmanifest',
  path: '/site.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglasDelTrucoRoute = ReglasDelTrucoRouteImport.update({
  id: '/reglas-del-truco',
  path: '/reglas-del-truco',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingCartasTrucoRoute = RankingCartasTrucoRouteImport.update({
  id: '/ranking-cartas-truco',
  path: '/ranking-cartas-truco',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAccountIdRoute = ProfileAccountIdRouteImport.update({
  id: '/profile_/$accountId',
  path: '/profile/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchSessionIdRoute = MatchSessionIdRouteImport.update({
  id: '/match/$sessionId',
  path: '/match/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbySessionIdRoute = LobbySessionIdRouteImport.update({
  id: '/lobby/$sessionId',
  path: '/lobby/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryMatchIdRoute = HistoryMatchIdRouteImport.update({
  id: '/history/$matchId',
  path: '/history/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRulesLangRoute = HelpRulesLangRouteImport.update({
  id: '/help_/rules/$lang',
  path: '/help/rules/$lang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/ranking-cartas-truco': typeof RankingCartasTrucoRoute
  '/register': typeof RegisterRoute
  '/reglas-del-truco': typeof ReglasDelTrucoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/truco-argentino': typeof TrucoArgentinoRoute
  '/truco-online': typeof TrucoOnlineRoute
  '/verify-email': typeof VerifyEmailRoute
  '/version.json': typeof VersionDotjsonRoute
  '/history/$matchId': typeof HistoryMatchIdRoute
  '/lobby/$sessionId': typeof LobbySessionIdRoute
  '/match/$sessionId': typeof MatchSessionIdRoute
  '/profile/$accountId': typeof ProfileAccountIdRoute
  '/help/rules/$lang': typeof HelpRulesLangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/ranking-cartas-truco': typeof RankingCartasTrucoRoute
  '/register': typeof RegisterRoute
  '/reglas-del-truco': typeof ReglasDelTrucoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/truco-argentino': typeof TrucoArgentinoRoute
  '/truco-online': typeof TrucoOnlineRoute
  '/verify-email': typeof VerifyEmailRoute
  '/version.json': typeof VersionDotjsonRoute
  '/history/$matchId': typeof HistoryMatchIdRoute
  '/lobby/$sessionId': typeof LobbySessionIdRoute
  '/match/$sessionId': typeof MatchSessionIdRoute
  '/profile/$accountId': typeof ProfileAccountIdRoute
  '/help/rules/$lang': typeof HelpRulesLangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/ranking-cartas-truco': typeof RankingCartasTrucoRoute
  '/register': typeof RegisterRoute
  '/reglas-del-truco': typeof ReglasDelTrucoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/truco-argentino': typeof TrucoArgentinoRoute
  '/truco-online': typeof TrucoOnlineRoute
  '/verify-email': typeof VerifyEmailRoute
  '/version.json': typeof VersionDotjsonRoute
  '/history/$matchId': typeof HistoryMatchIdRoute
  '/lobby/$sessionId': typeof LobbySessionIdRoute
  '/match/$sessionId': typeof MatchSessionIdRoute
  '/profile_/$accountId': typeof ProfileAccountIdRoute
  '/help_/rules/$lang': typeof HelpRulesLangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/forgot-password'
    | '/help'
    | '/inventory'
    | '/login'
    | '/magic-link'
    | '/matches'
    | '/profile'
    | '/ranking'
    | '/ranking-cartas-truco'
    | '/register'
    | '/reglas-del-truco'
    | '/reset-password'
    | '/site.webmanifest'
    | '/truco-argentino'
    | '/truco-online'
    | '/verify-email'
    | '/version.json'
    | '/history/$matchId'
    | '/lobby/$sessionId'
    | '/match/$sessionId'
    | '/profile/$accountId'
    | '/help/rules/$lang'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/forgot-password'
    | '/help'
    | '/inventory'
    | '/login'
    | '/magic-link'
    | '/matches'
    | '/profile'
    | '/ranking'
    | '/ranking-cartas-truco'
    | '/register'
    | '/reglas-del-truco'
    | '/reset-password'
    | '/site.webmanifest'
    | '/truco-argentino'
    | '/truco-online'
    | '/verify-email'
    | '/version.json'
    | '/history/$matchId'
    | '/lobby/$sessionId'
    | '/match/$sessionId'
    | '/profile/$accountId'
    | '/help/rules/$lang'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/forgot-password'
    | '/help'
    | '/inventory'
    | '/login'
    | '/magic-link'
    | '/matches'
    | '/profile'
    | '/ranking'
    | '/ranking-cartas-truco'
    | '/register'
    | '/reglas-del-truco'
    | '/reset-password'
    | '/site.webmanifest'
    | '/truco-argentino'
    | '/truco-online'
    | '/verify-email'
    | '/version.json'
    | '/history/$matchId'
    | '/lobby/$sessionId'
    | '/match/$sessionId'
    | '/profile_/$accountId'
    | '/help_/rules/$lang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MagicLinkRoute: typeof MagicLinkRoute
  MatchesRoute: typeof MatchesRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  RankingCartasTrucoRoute: typeof RankingCartasTrucoRoute
  RegisterRoute: typeof RegisterRoute
  ReglasDelTrucoRoute: typeof ReglasDelTrucoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SiteDotwebmanifestRoute: typeof SiteDotwebmanifestRoute
  TrucoArgentinoRoute: typeof TrucoArgentinoRoute
  TrucoOnlineRoute: typeof TrucoOnlineRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VersionDotjsonRoute: typeof VersionDotjsonRoute
  HistoryMatchIdRoute: typeof HistoryMatchIdRoute
  LobbySessionIdRoute: typeof LobbySessionIdRoute
  MatchSessionIdRoute: typeof MatchSessionIdRoute
  ProfileAccountIdRoute: typeof ProfileAccountIdRoute
  HelpRulesLangRoute: typeof HelpRulesLangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/version.json': {
      id: '/version.json'
      path: '/version.json'
      fullPath: '/version.json'
      preLoaderRoute: typeof VersionDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truco-online': {
      id: '/truco-online'
      path: '/truco-online'
      fullPath: '/truco-online'
      preLoaderRoute: typeof TrucoOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truco-argentino': {
      id: '/truco-argentino'
      path: '/truco-argentino'
      fullPath: '/truco-argentino'
      preLoaderRoute: typeof TrucoArgentinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site.webmanifest': {
      id: '/site.webmanifest'
      path: '/site.webmanifest'
      fullPath: '/site.webmanifest'
      preLoaderRoute: typeof SiteDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglas-del-truco': {
      id: '/reglas-del-truco'
      path: '/reglas-del-truco'
      fullPath: '/reglas-del-truco'
      preLoaderRoute: typeof ReglasDelTrucoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking-cartas-truco': {
      id: '/ranking-cartas-truco'
      path: '/ranking-cartas-truco'
      fullPath: '/ranking-cartas-truco'
      preLoaderRoute: typeof RankingCartasTrucoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/$accountId': {
      id: '/profile_/$accountId'
      path: '/profile/$accountId'
      fullPath: '/profile/$accountId'
      preLoaderRoute: typeof ProfileAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$sessionId': {
      id: '/match/$sessionId'
      path: '/match/$sessionId'
      fullPath: '/match/$sessionId'
      preLoaderRoute: typeof MatchSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$sessionId': {
      id: '/lobby/$sessionId'
      path: '/lobby/$sessionId'
      fullPath: '/lobby/$sessionId'
      preLoaderRoute: typeof LobbySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$matchId': {
      id: '/history/$matchId'
      path: '/history/$matchId'
      fullPath: '/history/$matchId'
      preLoaderRoute: typeof HistoryMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help_/rules/$lang': {
      id: '/help_/rules/$lang'
      path: '/help/rules/$lang'
      fullPath: '/help/rules/$lang'
      preLoaderRoute: typeof HelpRulesLangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MagicLinkRoute: MagicLinkRoute,
  MatchesRoute: MatchesRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  RankingCartasTrucoRoute: RankingCartasTrucoRoute,
  RegisterRoute: RegisterRoute,
  ReglasDelTrucoRoute: ReglasDelTrucoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SiteDotwebmanifestRoute: SiteDotwebmanifestRoute,
  TrucoArgentinoRoute: TrucoArgentinoRoute,
  TrucoOnlineRoute: TrucoOnlineRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VersionDotjsonRoute: VersionDotjsonRoute,
  HistoryMatchIdRoute: HistoryMatchIdRoute,
  LobbySessionIdRoute: LobbySessionIdRoute,
  MatchSessionIdRoute: MatchSessionIdRoute,
  ProfileAccountIdRoute: ProfileAccountIdRoute,
  HelpRulesLangRoute: HelpRulesLangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
